### ISSUE TITLE
Quick Create Ubuntu 18.04 does not allow regular Remote Desktop sessions

### ISSUE THREAD

**Issue by masters3d** [microsoft/linux-vm-tools#90] opened 2019-07-27 22:08 UTC
I found it very surprising that I was not able to connect to the Ubuntu VM using regular Remote desktop. There should be a way to do both just like in windows. 

Workaround is disabling `use_vsock`
https://stackoverflow.com/questions/57236407/cannot-rdp-to-ubuntu18-hyper-v-quick-start/57236408#57236408

related https://github.com/neutrinolabs/xrdp/issues/1124

**Comment by enricoreich** [comment] 2019-08-02 16:52
Can confirm that.
With `use_vsock=true` in `xrdp.ini` I'm not able to connect to my VM but with `use_vsock=false` it works!

VM: Debian buster 10.0
XRDP: v9.9
Host: Hyper-V on Windows 10 1903 (build 18362.267)

**Comment by cwilhit** [comment] 2020-01-30 18:11
Closing as this was by design in xrdp and they've resolved it in the latest version of xrdp (they support listneing on multiple channels now). You'll have to wait until Ubuntu ships with the new version of xrdp, or you can manually build it and configure it yourself in the mean time.

**Closed by cwilhit** 2020-01-30 18:11 UTC
