### ISSUE TITLE
New Version of UBUNTU 18.04 needs over 5GB RAM

### ISSUE THREAD

**Issue by dankseman** [microsoft/linux-vm-tools#71] opened 2018-10-20 21:52 UTC
I have been running the new version of 18.04 using Quick Create in Hyper-V and even in idle state it required over 5-6 GB of  RAM.  This is odd - even Windows 10 Pro idles at around 3GB or less.  Can anybody explain why?

**Comment by RonaldSwaine** [comment] 2018-11-22 01:45
Presuming you are looking at the Assigned Memory, and presuming by "Idle" you mean that you have a gnome session running (ie logged in) but have no applications going and no extra services loaded. With the memory buffer, and its infrequent allocation times... without modifications, this can be expected.

Ubuntu desktop minimal install + vm tools + minimal services (ssh,rdp,vnc,...) + ui extensions + a windows 10 theme, it doesn't break my minimum 2000mb startup memory before login.
Logged in, it uses around 4gb, then comes down to 2.4gb after logging out. Due to the Memory Buffer, the Assigned Memory (when having only just logged in) does seem to be a bit high, but is not a bug with Microsoft's vm tools, or even the dynamic memory. (check `top` for your gnome session) Its a being a piggy. I don't like it either. But I still use it for stuff, and expect it. There are some tweaks that can be done to help, but not anywhere near as much as you might need.

Here's what I say,

> If you want a full desktop experience, and not have leaner windows-side usage, buy more ram, or just setup another physical or externally hosted host. This could cost, I get it, it is what it is.
> 
> If you want a low ram gui, consider a different shell. You don't need to reinstall the OS either, just select installed ones from the login screen. Xfce anyone? Some people can be fooled by small distros' default shell-themes, but there's lots of eye candy no matter how small you go. opendesktop.org , deviantart.com ...
> 
> If you want the base OS's memory usage to be lower, use a lighter linux distro. 
> 
> If you just need to run some applications on the ubuntu system - like if you were testing an application or using it like an OS on-demand - you have more options, like making your own X session, openbox, or X over the network or even X forwarding over ssh. (running without a shell)


A warning though, if Enhanced session is what you need, in ubuntu or an os with a compatible xrdp compilation, you are going to need to customize the xrdp startup scripts for your shell, and potentially have to deal with any issues with session management (dealt with by sesman in the current Microsoft scripts). I'm stumbling down this path right now.

**Comment by cwilhit** [comment] 2021-01-28 18:32
This repo is being archived, so closing this issue.

**Closed by cwilhit** 2021-01-28 18:32 UTC
