### ISSUE TITLE
snapd malfunctioning on Hyper-V Ubuntu 18.04 Quick Create VM

### ISSUE THREAD

**Issue by masters3d** [microsoft/linux-vm-tools#89] opened 2019-07-25 16:10 UTC
```
     Setting up snapd (2.39.2+19.04)
     Installing new version of config file /etc/apparmor.d/usr.lib.snapd.snap-confine real ...
     md5sum: /etc/apparmor.d/usr.lib.snapd.snap-confine: No such file or directory snapd.failure.service is a
     disabled or static unit, not starting it.
     snapd.snap-repair.service is a disabled or static unit, not starting it.
```
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1835102

There is no way to use snap and even when i try to uninstall and reinstall snapd it wont let me.  This only seems to happen on the specific Quick Create image provided by windows 10. 

All the workarounds listed have not worked for me because snapd is needed to be in working condition in order to be uninstalled.

**Comment by SpitfireMk** [comment] 2019-08-28 20:59
I'm facing the same problem, both with 18.04 and 19.04.

This bug is already fixed according to this:
https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1828500

But it appears that the image provided using Quick Create hasn't been updated yet.

**Comment by gc435** [comment] 2019-09-26 00:31
Confirmed with 19.04.  Hope the image is updated soon, since the problem has already been fixed.

**Comment by xsebas21** [comment] 2019-09-26 17:17
I've faced the same problem, tried almost every workaround found, none worked.  Until I tried 
the below approach which was the only one that worked for me:

https://askubuntu.com/questions/1143436/snap-not-working/1147199#1147199

Basically you have to set the env variables:

```
sudo mkdir /etc/environment.d
sudo echo -e "PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/snap/bin"\nXDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/snapd/desktop"" > /etc/environment.d/60-snap-icons-and-bin.conf
sudo reboot now 
```

**Comment by gc435** [comment] 2019-09-26 17:21
This worked for me: https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1828500/comments/5

However, I just gave up and went back to Linux.  I applaud Microsoft's efforts, but there seems to always be friction and it's simpler to just use the real thing.

**Comment by xsebas21** [comment] 2019-09-26 17:35
Glad you could sort it out. There will always be some kind of problems, I agree on issues of this kind should have been addressed before its release. For some of us who rarely need Linux (or not at all, just playing around) this is a great approach though.

**Comment by SpitfireMk** [comment] 2019-09-26 17:48
> This worked for me: https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1828500/comments/5

This plus https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1828500/comments/8 did the trick for me.

**Comment by cwilhit** [comment] 2021-01-28 18:31
This repo is being archived, so closing this issue.

**Closed by cwilhit** 2021-01-28 18:31 UTC
