### ISSUE TITLE
Video remoting was disconnected

### ISSUE THREAD

**Issue by AbdullahA11** [microsoft/linux-vm-tools#109] opened 2020-04-10 19:02 UTC
Hi,

i'm working on my windows 10 pro laptop and i have installed hyper-vfor lab working. once i creat VM and tried to connect this massage is showing up " Video remoting was disconnected " " this session was disconnected. if you want to continue, try to connect again. if the proble persists, contact your system administrator."

i tride all solutions like disabling enhanced session mode or disable network card.

if anyone have any idea to help

**Comment by patrickave** [comment] 2020-04-15 13:24
I'm having the same issue as well.

**Comment by AbdullahA11** [comment] 2020-04-17 09:56
so anyone can help us

**Comment by patrickave** [comment] 2020-04-19 01:05
I figured it out @AbdullahA11 .  Are you setting your VM to auto log on?  If so, do NOT and then try the same username and password you set when the login screen comes up.

**Comment by AbdullahA11** [comment] 2020-04-19 11:58
it's my first VM @patrickave so i just creat vm and when i try to press on connect it'll show the same massage " Video remoting was disconnected " " this session was disconnected. if you want to continue, try to connect again. if the proble persists, contact your system administrator."

**Comment by patrickave** [comment] 2020-04-20 23:33
Then I dont know what youre dong wrong.

**Comment by ManickaP** [comment] 2020-05-11 10:02
I've encountered the same issue, Windows 10 19546 build, Manjaro KDE 20.0 VM. It starts to connect, let's me set the resolution, asks for credentials in XRDP windows and shortly after that crashes with the above mentioned error.

**Comment by ManickaP** [comment] 2020-05-11 10:18
I found the root cause and got it working. The xstart command to start kde plasma has changed: https://wiki.archlinux.org/index.php/KDE#Starting_Plasma
You need to change `~/.xinitrc` to reflect that `startkde` --> `startplasma-x11`. In my case I had to change line with `DEFAULT_SESSION`:
```
DEFAULT_SESSION=startplasma-x11
```

**Comment by cwilhit** [comment] 2021-01-28 18:29
This repo is being archived, so closing this issue.

**Closed by cwilhit** 2021-01-28 18:29 UTC
