### ISSUE TITLE
Auto resolution Ubuntu 19.04

### ISSUE THREAD

**Issue by squizee** [microsoft/linux-vm-tools#93] opened 2019-08-29 17:15 UTC
Is that script for Ubuntu 18.04 should work for 19.04? If so, that won't :( Still fixed resolution with no xrdp loging...

**Comment by pyro-dev** [comment] 2019-11-08 02:20
Same problem here. The enhanced session doesn't work when using the Ubuntu 19.04 image to create the VM. Actually, starting from a 18.10 LTS image (where ES works) and then upgrading to 19.04 seems to break it as well.
The install.sh script available in this repository runs fine without any error, but enhanced mode is still not available.

**Comment by user135711** [comment] 2019-12-03 10:45
DId you get it to work? I don't want to waste time but the Quick create keeps freezing on download so I have to do 19.04 manually.

**Comment by pyro-dev** [comment] 2019-12-09 11:09
No success for me so far. I'm giving up on this for the time being, since it's not that critical to me, but a working enhanced mode would be pretty nice. I had no success with 19.10 either.
The Quick Create however works on my machines, I have no freezing issue at all.

**Comment by cyberluke** [comment] 2019-12-11 14:51
The 18.04 was pain in the ass. Even the built-in image, I had to solve enhanced mode and it took me like 3 days. Not working out of the box. One of my mistakes was that I set autologin during the install, which then makes problems.

Now I installed 19.10. It worked once in Enhanced mode right after install. But today I boot and Enhanced mode does not work again. Now I solved it with this: https://stackoverflow.com/questions/57236407/cannot-rdp-to-ubuntu18-hyper-v-quick-start/57236408#57236408 ...you can connect only using RDP (Remote Desktop in Windows), but you get the enhanced mode.

My recommendation is purchase X410, install Ubuntu 19 with VSOCK and use this procedure to set up seamless window integration: https://token2shell.com/howto/x410/quick-testing-vsock-hyper-v-support-in-x410/

This repository totally sucks. It is not even updated, while Hyper-V contains 19 custom image already and this custom image still have bugs like VSOCK vs TCP fighting.

**Comment by c-goes** [comment] 2020-02-26 16:44
While the 18.04 script works for 19.10, it won't (yet) for 20.04.
The problem is identical to Arch (#94)

**Comment by agilleyrh** [comment] 2020-04-24 15:55
Also trying this on 20.04, it is identical to the issue mentioned above for Arch but 20.04 seems to have the newer version of xrdp. I was able to get this installed but the xrdp service will not start.

**Comment by cwilhit** [comment] 2021-01-28 18:31
This repo is being archived, so closing this issue.

**Closed by cwilhit** 2021-01-28 18:31 UTC
